@startuml starcraft

abstract Star

abstract Zerg extends Unit implements Recovery
abstract Terran extends Unit
abstract Protoss extends Unit implements Shield
abstract Unit extends Star
abstract Structure extends Star
interface TerranStructure extends Terran implements Structure
interface ZergStructure extends Zerg implements Structure
interface ProtossStructure extends Protoss implements Structure
interface Bionic
interface Mechanic
interface Recovery
interface Shield
interface Mineral


class Marine extends Terran implements Bionic
class Medic extends Terran implements Bionic{
    RepairBionicTerranUnit
}
class Tank extends Terran implements Mechanic
class Vulture extends Terran implements Mechanic
class Scv extends Terran implements Bionic, Mechanic, Mineral{
    RepairMechanicTerranUnit
    GetMineral
}

class Zealot extends Protoss implements Bionic
class Dragun extends Protoss implements Mechanic

@enduml